### ISSUE TITLE
The current .NET SDK does not support targeting .NET Core 2.1.  

### ISSUE THREAD

**Issue by Rstar-Yan** [YahuiWong/jenkins-dotnet-core#1]
我用你的dockerfile 构建的jenkins 后  构建的命令 好像dotnet 的版本不对。  但是我进入容器检查了sdk也是2.1.4 有什么解决方案吗
The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.

**Comment by YahuiWong** [comment]
现在已经支持  .NET Core 2.1 可以使用最新的部署试试看

**Comment by Rstar-Yan** [comment]
谢谢
